version: "3.7"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "19002:19002"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_URL=http://locahost:9000
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:19002
      - MINIO_CONSOLE_PORT=9001

    command:  minio server /data --console-address ":19002"

volumes:
  minio_data: