# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import imagegeneration_pb2 as imagegeneration__pb2


class ImageGenerationStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateImage = channel.unary_unary(
                '/proto.imagegeneration.ImageGeneration/GenerateImage',
                request_serializer=imagegeneration__pb2.ImageGenerationRequest.SerializeToString,
                response_deserializer=imagegeneration__pb2.ImageGenerationResponse.FromString,
                )
        self.Status = channel.unary_unary(
                '/proto.imagegeneration.ImageGeneration/Status',
                request_serializer=imagegeneration__pb2.EmptyRequest.SerializeToString,
                response_deserializer=imagegeneration__pb2.StatusResponse.FromString,
                )


class ImageGenerationServicer(object):
    """Service definition
    """

    def GenerateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageGenerationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=imagegeneration__pb2.ImageGenerationRequest.FromString,
                    response_serializer=imagegeneration__pb2.ImageGenerationResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=imagegeneration__pb2.EmptyRequest.FromString,
                    response_serializer=imagegeneration__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.imagegeneration.ImageGeneration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageGeneration(object):
    """Service definition
    """

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.imagegeneration.ImageGeneration/GenerateImage',
            imagegeneration__pb2.ImageGenerationRequest.SerializeToString,
            imagegeneration__pb2.ImageGenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.imagegeneration.ImageGeneration/Status',
            imagegeneration__pb2.EmptyRequest.SerializeToString,
            imagegeneration__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
