# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagegeneration.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15imagegeneration.proto\x12\x15proto.imagegeneration\x1a\x1egoogle/protobuf/wrappers.proto\"*\n\nTextPrompt\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x02\"\x88\x02\n\x16ImageGenerationRequest\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x37\n\x0ctext_prompts\x18\x03 \x03(\x0b\x32!.proto.imagegeneration.TextPrompt\x12\r\n\x05steps\x18\x04 \x01(\x05\x12\x0f\n\x07samples\x18\x05 \x01(\x05\x12\x11\n\tcfg_scale\x18\x06 \x01(\x02\x12\x1c\n\x14\x63lip_guidance_preset\x18\x07 \x01(\t\x12\x0f\n\x07sampler\x18\x08 \x01(\t\x12\x0c\n\x04seed\x18\t \x01(\x05\x12\x14\n\x0cstyle_preset\x18\n \x01(\t\x12\x10\n\x08model_id\x18\x0b \x01(\t\"%\n\x05Image\x12\x0e\n\x06\x62\x61se64\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\x05\"]\n\x17ImageGenerationResponse\x12,\n\x06images\x18\x01 \x03(\x0b\x32\x1c.proto.imagegeneration.Image\x12\x14\n\x0c\x66inishReason\x18\x02 \x01(\t\"~\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10\x63urrent_model_id\x18\x03 \x01(\t\x12\x31\n\x0cmemory_usage\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\"\x0e\n\x0c\x45mptyRequest2\xd7\x01\n\x0fImageGeneration\x12n\n\rGenerateImage\x12-.proto.imagegeneration.ImageGenerationRequest\x1a..proto.imagegeneration.ImageGenerationResponse\x12T\n\x06Status\x12#.proto.imagegeneration.EmptyRequest\x1a%.proto.imagegeneration.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imagegeneration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXTPROMPT']._serialized_start=80
  _globals['_TEXTPROMPT']._serialized_end=122
  _globals['_IMAGEGENERATIONREQUEST']._serialized_start=125
  _globals['_IMAGEGENERATIONREQUEST']._serialized_end=389
  _globals['_IMAGE']._serialized_start=391
  _globals['_IMAGE']._serialized_end=428
  _globals['_IMAGEGENERATIONRESPONSE']._serialized_start=430
  _globals['_IMAGEGENERATIONRESPONSE']._serialized_end=523
  _globals['_STATUSRESPONSE']._serialized_start=525
  _globals['_STATUSRESPONSE']._serialized_end=651
  _globals['_EMPTYREQUEST']._serialized_start=653
  _globals['_EMPTYREQUEST']._serialized_end=667
  _globals['_IMAGEGENERATION']._serialized_start=670
  _globals['_IMAGEGENERATION']._serialized_end=885
# @@protoc_insertion_point(module_scope)
